SELECT  *
FROM EMPLOYEES
WHERE FIRST_NAME = 'David'; /* 3 */ 

SELECT  *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50 
AND SALARY > 4000; /* 4 */ 

SELECT  *
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (20, 30); 

SELECT  *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20 OR DEPARTMENT_ID = 30; /* 5 */ 

SELECT  *
FROM EMPLOYEES
WHERE FIRST_NAME like '_a%a'; /* 6 */ 

SELECT  *
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (50, 80) 
AND COMMISSION_PCT is not NULL
ORDER BY 4; /* 7 */ 

SELECT  *
FROM EMPLOYEES
WHERE FIRST_NAME like '%n%n%'; /* 8 */ 

SELECT  *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%_____%'
ORDER BY DEPARTMENT_ID DESC NULLS LAST; /* 9 */ 

SELECT  *
FROM EMPLOYEES
WHERE ( SALARY BETWEEN 3000 AND 7000 ) 
AND (COMMISSION_PCT IS NULL) 
AND JOB_ID IN ('PU_CLERK', 'ST_MAN', 'ST_CLERK'); /* 10 */ 

SELECT  *
FROM EMPLOYEES
WHERE FIRST_NAME like '%\%%' ESCAPE '\'; /* 11 */ 

SELECT  JOB_ID 
       ,FIRST_NAME 
       ,SALARY
FROM EMPLOYEES
WHERE (EMPLOYEE_ID >= 120 AND JOB_ID != ' IT_PROG ')
ORDER BY JOB_ID, FIRST_NAME desc;  